package com.velora.api.catalog.web.admin;

import com.velora.api.catalog.dto.admin.ImageResponse;
import com.velora.api.catalog.dto.admin.ImageUpdateRequest;
import com.velora.api.catalog.dto.admin.ProductAdminResponse;
import com.velora.api.catalog.dto.admin.ProductCreateRequest;
import com.velora.api.catalog.dto.admin.ProductUpdateRequest;
import com.velora.api.catalog.service.admin.ProductAdminService;
import com.velora.api.catalog.service.admin.ProductImageService;
import com.velora.api.common.dto.PageResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.util.List;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Pageable;
import org.springframework.data.web.PageableDefault;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@Tag(name = "Admin — Products", description = "Product management. Requires ROLE_ADMIN.")
@SecurityRequirement(name = "bearerAuth")
@RestController
@RequestMapping("/api/v1/admin/products")
public class AdminProductController {

    private final ProductAdminService productService;
    private final ProductImageService imageService;

    public AdminProductController(ProductAdminService productService,
                                  ProductImageService imageService) {
        this.productService = productService;
        this.imageService = imageService;
    }

    @Operation(summary = "List all products including drafts and archived")
    @GetMapping
    public PageResponse<ProductAdminResponse> list(
            @ParameterObject @PageableDefault(size = 20) Pageable pageable) {
        return productService.list(pageable);
    }

    @Operation(summary = "Get one product")
    @GetMapping("/{id}")
    public ProductAdminResponse get(@PathVariable Long id) {
        return productService.get(id);
    }

    @Operation(summary = "Create a product",
            description = "Created as DRAFT. Add variants, then publish. "
                    + "The slug and Arabic search text are generated by the server.")
    @PostMapping
    public ResponseEntity<ProductAdminResponse> create(
            @Valid @RequestBody ProductCreateRequest request) {
        return ResponseEntity.status(HttpStatus.CREATED).body(productService.create(request));
    }

    @Operation(summary = "Update a product")
    @PutMapping("/{id}")
    public ProductAdminResponse update(@PathVariable Long id,
                                       @Valid @RequestBody ProductUpdateRequest request) {
        return productService.update(id, request);
    }

    @Operation(summary = "Publish",
            description = "Refused unless the product has at least one variant and an Arabic name.")
    @PatchMapping("/{id}/publish")
    public ProductAdminResponse publish(@PathVariable Long id) {
        return productService.publish(id);
    }

    @Operation(summary = "Unpublish — back to draft")
    @PatchMapping("/{id}/unpublish")
    public ProductAdminResponse unpublish(@PathVariable Long id) {
        return productService.unpublish(id);
    }

    @Operation(summary = "Archive",
            description = "Soft delete. Order lines reference this product forever, "
                    + "so the row is never removed.")
    @PatchMapping("/{id}/archive")
    public ProductAdminResponse archive(@PathVariable Long id) {
        return productService.archive(id);
    }

    @Operation(summary = "Duplicate", description = "Copies content but not SKUs or stock")
    @PostMapping("/{id}/duplicate")
    public ResponseEntity<ProductAdminResponse> duplicate(@PathVariable Long id) {
        return ResponseEntity.status(HttpStatus.CREATED).body(productService.duplicate(id));
    }

    // -------------------------------------------------------------------- images

    @Operation(summary = "List images")
    @GetMapping("/{id}/images")
    public List<ImageResponse> listImages(@PathVariable Long id) {
        return imageService.list(id);
    }

    @Operation(summary = "Upload an image",
            description = "JPEG, PNG, WebP or AVIF, up to 5 MB. "
                    + "Attach a variantId so the gallery swaps when the colour changes.")
    @PostMapping(value = "/{id}/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<ImageResponse> uploadImage(
            @PathVariable Long id,
            @RequestPart("file") MultipartFile file,
            @Parameter(description = "Optional — attach to one variant")
            @RequestParam(required = false) Long variantId) {

        return ResponseEntity.status(HttpStatus.CREATED)
                .body(imageService.upload(id, file, variantId));
    }

    @Operation(summary = "Update image metadata — alt text, order, main flag")
    @PutMapping("/{id}/images/{imageId}")
    public ImageResponse updateImage(@PathVariable Long id,
                                     @PathVariable Long imageId,
                                     @Valid @RequestBody ImageUpdateRequest request) {
        return imageService.update(id, imageId, request);
    }

    @Operation(summary = "Delete an image")
    @DeleteMapping("/{id}/images/{imageId}")
    public ResponseEntity<Void> deleteImage(@PathVariable Long id, @PathVariable Long imageId) {
        imageService.delete(id, imageId);
        return ResponseEntity.noContent().build();
    }
}
